loggin:
  config: classpath:log4j2.xml
  
spring:
  oauth:
    oauthUri: https://localhost:8443/agent-oauth2/oauth/token
    checkTokenUri: https://localhost:8443/agent-oauth2/oauth/check_token
    clientId: console
    secret: j1d1sec.c0m
  mongodb:
    uri: mongodb://root:mongodb%40cl0vdsec.c0m@127.0.0.1:27017/admin
server:
  keystorePath: /usr/local/las/program/tomcat7/conf/server.keystore
  keystorePassword: changeit