loggin:
  config: classpath:log4j2.xml
  
spring:
  oauth:
    datasource:
      url: jdbc:mysql://localhost:3306/oauth?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
      username: root
      password: 
      driverClassName: com.mysql.jdbc.Driver
    oauthUri: https://localhost/agent-oauth2/oauth/token
    checkTokenUri: https://localhost/agent-oauth2/oauth/check_token
    clientId: proxy_console
    secret: 
  host:
    datasource:
      url: jdbc:mysql://localhost:3306/proxy_console?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
      username: root
      password: 
      driverClassName: com.mysql.jdbc.Driver
      
server:
  keystorePath: /usr/local/tomcat/conf/server.keystore
  keystorePassword: changeit